name: Manual Deploy from Latest Release

on:
  workflow_dispatch:
    inputs:
      target:
        description: '출시 대상 선택'
        required: true
        default: 'both'
        type: choice
        options:
          - both
          - chrome
          - firefox

permissions:
  contents: read

jobs:
  deploy-store:
    runs-on: ubuntu-latest
    steps:
      - name: Download Latest Release Assets
        id: release
        uses: robinraju/release-downloader@28fc21f50d76778e7023361aa1f863e717d3d56f # v1.13
        with:
          latest: true
          fileName: "*"

      - name: Verify Release Asset Checksums
        run: sha256sum --check SHA256SUMS

      - name: Identify Extension Files
        id: files
        env:
          RELEASE_TAG: ${{ steps.release.outputs.tag_name }}
        run: |
          CHROME_FILE="kosteam-chrome-${RELEASE_TAG}.zip"
          FIREFOX_FILE="kosteam-firefox-${RELEASE_TAG}.zip"
          
          echo "Found Chrome File: $CHROME_FILE"
          echo "Found Firefox File: $FIREFOX_FILE"
          
          if [[ "${{ github.event.inputs.target }}" == "both" || "${{ github.event.inputs.target }}" == "chrome" ]]; then
            if [ ! -f "$CHROME_FILE" ]; then
              echo "Error: Chrome extension file not found."
              exit 1
            fi
            echo "chrome_path=$CHROME_FILE" >> $GITHUB_OUTPUT
          fi
          
          if [[ "${{ github.event.inputs.target }}" == "both" || "${{ github.event.inputs.target }}" == "firefox" ]]; then
            if [ ! -f "$FIREFOX_FILE" ]; then
              echo "Error: Firefox extension file not found."
              exit 1
            fi
            echo "firefox_path=$FIREFOX_FILE" >> $GITHUB_OUTPUT
          fi

      - name: Upload to Chrome Web Store
        if: github.event.inputs.target == 'both' || github.event.inputs.target == 'chrome'
        uses: mnao305/chrome-extension-upload@fdfe79400af990f5145a319e834aee64907ccff4 # v6.0.0
        with:
          file-path: ${{ steps.files.outputs.chrome_path }}
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          publish: true

      - name: Sign & Upload to Firefox Add-ons
        if: github.event.inputs.target == 'both' || github.event.inputs.target == 'firefox'
        uses: wdzeng/firefox-addon@3184ee491b500e080885e046051366a4228c6e5d # v1
        with:
          addon-guid: 'alevo0918@gmail.com'
          xpi-path: ${{ steps.files.outputs.firefox_path }}
          jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
          jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}
